change yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -35,9 +35,17 @@ jobs:
           class_name=$(echo $file | sed 's|.class||; s|/||; s|.||')
           echo "Class name: $class_name"
 
-          java $class_name
+          #java $class_name
           #grep 'public static void main'　見つけた場合、「0」ステータスコードが返され、見つからなかった場合、「1」ステータスコードが返される
-          
+          if javap -public $class_name | grep 'public static void main' > /dev/null; then
+            echo $?
+            echo "Found main method in $class_name, running it..."
+            java $class_name
+            #break
+          else
+            echo $?
+            echo "Not Found main method in $class_name."
+          fi
 
           echo
         done
